### ISSUE TITLE
Generate user avatars

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#148]

**Comment by SamZhang02** [comment]
do we lock each user with an avatar or should we randomly generate one every time someone writes a review and attach it to only the review?

**Comment by terror** [comment]
> do we lock each user with an avatar or should we randomly generate one every time someone writes a review and attach it to only the review? 

Both would be pretty straight forward to implement, but there's the question if we associate images with users it might not allow for a truly anonymous platform, i.e. a user might somehow find out the true identity of someone behind an image, and thus knows the person who wrote all reviews with that same image.

I could be overthinking this though 🤔

**Comment by terror** [comment]
Closing in favour of #365
