### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#178]
- [x] #150
- [x] #210
- [x] #136
- [x] #212
- [x] #135
- [x] #48
- [x] #161
- [x] #207 
- [x] #205
- [x] #98 
- [x] #231
- [x] #213 
- [x] #149 
- [x] #245 
- [x] #215
- [x] #197
- [x] #164
- [x] #243  
- [x] #208  
- [ ] #244 
- [ ] #209 
- [x] #268

**Comment by SamZhang02** [comment]
deployment after we check all these 👀

**Comment by SamZhang02** [comment]
>  Other field for instructors (?)

```
reviews :  Review[]
```
seems like a good idea since we are showing them on the instructor page

**Comment by SamZhang02** [comment]
How do you feel about a 
```
courses: Course[]
```
under `Instructor`?

Then on the instructor page we can display reviews given to that instructor + the courses that they are currently teaching

**Comment by terror** [comment]
> How do you feel about a
> 
> ```
> courses: Course[]
> ```
> 
> under `Instructor`?
> 
> Then on the instructor page we can display reviews given to that instructor + the courses that they are currently teaching

We can get all of this information by extending some of the routes we have, i.e. for review we'd do /reviews?instructor_name=... and for courses we'd do /courses?instructor_name=... or for this one we'd add it to the body and also add an instructor filter to the explore page

**Comment by terror** [comment]
Alpha is done, going to move incomplete items over to the Beta launch tracking issue 🚀
