### ISSUE TITLE
Fix overflowing search results and footer interaction

### ISSUE THREAD

**Issue by SamZhang02** [terror/mcgill.courses#203]
https://github.com/terror/mcgill.courses/assets/112342947/d05cb1a1-7698-4e45-bd2c-91d7d108c42b

**Comment by terror** [comment]
Is this a z-index issue? I was thinking we could also limit the search results even more, seems a bit excessive.

**Comment by SamZhang02** [comment]
> Is this a z-index issue?

z-index is one of the issue, but i was also thinking why this footer is sticked while im scrolling up

> we could also limit the search results even more

Yeah i also think its too much right now, i'll reduce it

**Comment by SamZhang02** [comment]
We reduced the search result a while back, this is not really an issue anymore
