### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#302]
- [x] #314 
- [x] #306 
- [x] #319 
- [x] #323
- [x] #322
- [x] #316   
- [x] #308 
- [x] #332
- [x] #297  
- [x] #312 
- [ ] #295 
- [ ] #223 
- [ ] #294 
- [ ] #324 
- [ ] #260 
- [ ] #255 
- [ ] #331 
- [ ] #160 
- [ ] #315 
- [ ] #209 
- [ ] #326 
- [ ] #304 
- [ ] #329 
- [ ] #242 
- [ ] #303 
- [ ] #346 
- [ ] #301 
- [ ] #244 
- [ ] #307 
- [ ] #338 
- [ ] #333 
- [ ] #339

**Comment by SamZhang02** [comment]
not working on any of these because i aint no beta male 😤

**Comment by terror** [comment]
Closing in favour of using the board
