### ISSUE TITLE
Fix schedule open icon overflow on small screens

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#312]
Specifically when you get to mobile size, the open icon renders outside of the schedule box

<img width="395" alt="Screenshot 2023-06-21 at 8 09 34 PM" src="https://github.com/terror/mcgill.courses/assets/31192478/e1b5d162-6aba-4361-8f71-d70e1d1cebc3">

**Comment by SamZhang02** [comment]
damn wtf 💀
