### ISSUE TITLE
Make course search faster

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#387]
MongoDB full-text search is quite slow (visible latency), could we leverage something else to make it faster? Some options:
- Redis full-text search module, in-memory so everything is super quick to access => see [mcgill.wtf](https://mcgill.wtf/) for an example
- Client-side search? Does `fuse.js` blow up if we try to search through all of our course records => `10,000`? Or could we use https://github.com/lucaong/minisearch?
- Atlas search, this is a MongoDB cloud feature - supports fuzzy search and stuff, could be something
- https://github.com/quickwit-oss/tantivy

**Comment by SamZhang02** [comment]
- [ ] (discovery) FlexSearch
