### ISSUE TITLE
Fix histogram display on specific screen sizes

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#423]
At certain screen sizes the histogram comes off of the course card

<img width="1081" alt="Screenshot 2023-09-22 at 4 16 51 PM" src="https://github.com/terror/mcgill.courses/assets/31192478/fe44891f-ed3f-4190-8317-a7ad94017e35">

**Comment by JeffDotPng** [comment]
I can't reproduce (?)

**Comment by SamZhang02** [comment]
> I can't reproduce (?)

approximately 1285 * 1251px is like that for me

**Comment by terror** [comment]
Ya'll Got The Tiny Monitors

**Comment by SamZhang02** [comment]
LMAO i legit just got a 4k monitor an hour ago and hopped on to see if i can now reproduce, looks like i just need to add some margins

**Comment by SamZhang02** [comment]
@terror the pr fixes it on my screen, can you check on yours if its good
