### ISSUE TITLE
Inquiry on External PRs for Feature Requests

### ISSUE THREAD

**Issue by hanzili** [terror/mcgill.courses#484]
I'm interested in contributing to this project and have read the CONTRIBUTING file and the CC0-1.0 license details. I'm looking to clarify if external pull requests are currently welcome, particularly for feature requests listed in the issues.

Are you accepting PRs for these feature requests from external contributors?

**Comment by hanzili** [comment]
Hello,

I'm setting up this project for development and noticed that `MS_CLIENT_ID`, `MS_CLIENT_SECRET`, and `MS_REDIRECT_URI` are required for the Microsoft Identity setup. These aren't available in the current documentation or setup files.

Could you provide guidance or the necessary steps for contributors to obtain or set these variables for local development?

Thanks for your help!

**Comment by JeffDotPng** [comment]
Hi, thanks for the interest (kind of late response haha, happy new year)

To setup the environment variables for Microsoft OAuth you'll want to:
1. Go to the Azure dashboard, click "Microsoft Entra ID"
2. Click "Manage Tenants" and create a new tenant, then switch to your newly created tenant
3. In your new tenant, from the sidebar go to "App registrations"
4. When creating the new registration pick "Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant)" for supported account types
![image](https://github.com/terror/mcgill.courses/assets/47371088/4b11eb72-0ae7-417c-bd20-c2b56c0c38e5)
5. For the redirect URI put "http://localhost:8000/api/auth/authorized", this is the value for `MS_REDIRECT_URI`
6. `MS_CLIENT_ID` will be under "Application (client) ID" in the app registration overview
7. To create the client secret, click on "Client credentials" in the app registration overview
8. Create a new secret, this will be `MS_CLIENT_SECRET`

Let me know if you have run into issues during the process.

**Comment by SamZhang02** [comment]
Hi @hanzili , can I close this issue? :)

**Comment by hanzili** [comment]
Great thanks for the guidance, the issue can now be closed!
