### ISSUE TITLE
Support Multiple Professors

### ISSUE THREAD

**Issue by Vermillion-Chen** [terror/mcgill.courses#521]
Some courses are taught by multiple professors, but the website only shows one and their associated ratings. I believe it would be beneficial to be able to support multiple, and see everyone's ratings. 

For example, [Phgy 313 ](https://mcgill.courses/course/phgy-313) only lists Judith Mandl but it has several professors on the McGill eCalendar. 
![image](https://github.com/terror/mcgill.courses/assets/83526116/35db67c8-d0a7-4662-817f-f684b60e59a6)

https://mcgill.courses/course/phgy-313

**Comment by 39bytes** [comment]
This isn't particularly difficult to add from a code standpoint, but it's hard to come up with an elegant way to display all of the names in the UI without it becoming really cluttered (in fact, this did come up in development, but we just we just went with just displaying the first prof's name for now.) Do you have any suggestions for the UI part?

**Comment by Vermillion-Chen** [comment]
My thoughts would be to just have all the professors' names in that bubble style, with wrapping inside a container. And showing all reviews and overall rating is fine, but when a user clicks on a professor's name, it could automatically filter the reviews by the professor and dynamically calculate the average ratings and difficulties.

**Comment by 39bytes** [comment]
> My thoughts would be to just have all the professors' names in that bubble style, with wrapping inside a container. And showing all reviews and overall rating is fine, but when a user clicks on a professor's name, it could automatically filter the reviews by the professor and dynamically calculate the average ratings and difficulties.

That could work, it might get very crowded on things like biology courses with like 10 profs though.
Filtering reviews + dynamically calculating average ratings/difficulty is already supported by using the review filters, so there's no need for that.
