### ISSUE TITLE
Sort user reviews from most recent to least on profile page

### ISSUE THREAD

**Issue by SamZhang02** [terror/mcgill.courses#537]
![CleanShot 2024-04-24 at 23 39 43@2x](https://github.com/terror/mcgill.courses/assets/112342947/73bb0adb-89f5-4b4a-819e-623a27d17d11)

Small thing but sorting from most recent on top probably makes more sense, currently its least recent on top

**Comment by terror** [comment]
This is pretty easy to do now, just add `sorted: true` to the request made from the profile page
