### ISSUE TITLE
Fix failing mongodb installation in our CI pipeline

### ISSUE THREAD

**Issue by terror** [terror/mcgill.courses#599]
<img width="853" alt="Screenshot 2024-08-28 at 2 10 45 PM" src="https://github.com/user-attachments/assets/ea9dcae3-3849-4cc7-9b10-7ea794208d51">

**Comment by SamZhang02** [comment]
i think it fixed by itself, all tests are passing now?

**Comment by terror** [comment]
Yeah this has fixed itself apparently 💀
