### ISSUE TITLE
Feature Request for frontend: Indicator for pre-existing reviews from ratemyprof 

### ISSUE THREAD

**Issue by DominicPhung** [terror/mcgill.courses#600]
What the title says. Either tag every review before a specific date (when mcgill.courses was launched), or find a way to tag scraped vs not scraped reviews. 

Can be an icon, or a different background color, or just a string saying it's from RMP.

It could help discern between potentially spammy or useless reviews versus ones reviwed on the site directly IMHO

**Comment by terror** [comment]
We think this is a great idea, we'll get to work on it!
